[package]
name = "motoko_parse"
version = "0.1.0"
edition = "2018"

[dependencies]
combine = { version = "4.6", features = ["regex", "std"] }
rug = "1.13"
pretty_assertions = "1.0"

[[test]]
name = "basic-tests"
path = "tests/basic.rs"
