[package]
name = "motoko_parse"
version = "0.1.0"
edition = "2018"

[dependencies]
combine = { version = "4.6", features = ["regex"] }
rug = "1.13"
pretty_assertions = "1.0"

[dev-dependencies]
lazy_static = "1.4.0"
